CREATE TABLE AVALICAO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    DATA_AVALIACAO DATE NOT NULL,
    APROVEITAMENTO INTEGER NOT NULL,
    ID_CANDIDATO INTEGER NOT NULL,
    ID_PROVA INTEGER NOT NULL,
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA(ID) ON DELETE CASCADE,
)

CREATE TABLE CANDIDATO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    SENHA VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL
)

CREATE TABLE PROVA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TITULO VARCHAR(80) NOT NULL,
    PERCENTUAL_PROVA INTEGER NOT NULL
)

CREATE TABLE PROVA_QUESTAO (
    ID_PROVA INTEGER PRIMARY KEY NOT NULL,
    ID_QUESTAO INTEGER PRIMARY KEY NOT NULL,
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_QUESTAO) REFERENCES QUESTAO(ID) ON DELETE CASCADE
)

CREATE TABLE QUESTAO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DESCRICAO VARCHAR(400) NOT NULL,
    ALTERNATIVA_1 VARCHAR(400) NOT NULL,
    ALTERNATIVA_2 VARCHAR(400) NOT NULL,
    ALTERNATIVA_3 VARCHAR(400) NOT NULL,
    ALTERNATIVA_4 VARCHAR(400) NOT NULL,
    ALTERNATIVA_5 VARCHAR(400) NOT NULL,
    RESPOSTA INTEGER NOT NULL,
    ID_SENIORIDADE INTEGER NOT NULL,
    ID_TIPO_QUESTAO INTEGER NOT NULL,
    FOREIGN KEY (ID_SENIORIDADE) REFERENCES SENIORIDADE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_TIPO_QUESTAO) REFERENCES TIPO_QUESTAO(ID) ON DELETE CASCADE,
)

CREATE TABLE SENIORIDADE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DESCRICAO VARCHAR(80) NOT NULL
)

INSERT INTO SENIORIDADE VALUES ('Estagiário');
INSERT INTO SENIORIDADE VALUES ('Júnior');
INSERT INTO SENIORIDADE VALUES ('Pleno');
INSERT INTO SENIORIDADE VALUES ('Sênior');

CREATE TABLE TIPO_QUESTAO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DESCRICAO VARCHAR(80) NOT NULL
)

INSERT INTO TIPO_QUESTAO VALUES ('Requisito');
INSERT INTO TIPO_QUESTAO VALUES ('Análise e projeto');
INSERT INTO TIPO_QUESTAO VALUES ('Codificação');
INSERT INTO TIPO_QUESTAO VALUES ('Teste');
INSERT INTO TIPO_QUESTAO VALUES ('Arquitetura');