CREATE TABLE AVALICAO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    DATA_AVALIACAO DATE NOT NULL,
    APROVEITAMENTO INTEGER NOT NULL,
    ID_CANDIDATO INTEGER NOT NULL,
    ID_PROVA INTEGER NOT NULL,
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA(ID) ON DELETE CASCADE,
)