CREATE TABLE AVALICAO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    DATA_AVALIACAO DATE NOT NULL,
    APROVEITAMENTO INTEGER NOT NULL,
    ID_CANDIDATO INTEGER NOT NULL,
    ID_PROVA INTEGER NOT NULL,
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA(ID) ON DELETE CASCADE,
)

CREATE TABLE CANDIDATO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    SENHA VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL
)

CREATE TABLE PROVA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TITULO VARCHAR(80) NOT NULL,
    PERCENTUAL_PROVA INTEGER NOT NULL
)

CREATE TABLE PROVA_QUESTAO (
    ID_PROVA INTEGER PRIMARY KEY NOT NULL,
    ID_QUESTAO INTEGER PRIMARY KEY NOT NULL,
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_QUESTAO) REFERENCES QUESTAO(ID) ON DELETE CASCADE
)